### ISSUE TITLE
Missing text on provided test tables

### ISSUE THREAD

**Issue by francisdb** [jsm174/vpx-standalone-scripts#100]
I would try to fall back to the system default font?

Widows

<img width="955" alt="image" src="https://github.com/jsm174/vpx-standalone-scripts/assets/161305/851facd1-5495-4c82-b71b-d4216ee944d9">

Linux

![image](https://github.com/jsm174/vpx-standalone-scripts/assets/161305/5bb7e199-a558-490c-b2e3-9b942912d978)

**Comment by jsm174** [comment]
Standalone does not have the Windows font system ported. 

No tables really seem to use it except for debugging purposes.

Maybe we could somehow simulate it with SDL_TTF?

As it's not really a necessity at this time, closing.

**Comment by francisdb** [comment]
just linking #104 as sonic also uses this
