### ISSUE TITLE
Create exclusive fullscreen window last

### ISSUE THREAD

**Issue by francisdb** [jsm174/vpx-standalone-scripts#101]
Ubuntu / 2 screen setup
I have been thinking why my playfield window is being minimized on startup

My guess is the following:

1. Playfield window is created fullscreen.
2. DMD / B2S windows are created next.
3. Since the Playfield is in exclusive fullscreen it is minimized to show the other windows.

So probably creating the playfield window as last window would solve the issue.

Is there an easy way to make this change to test?

**Comment by jsm174** [comment]
@francisdb Is this still an issue? I tested on my Ubuntu and it seems to work fine.

**Comment by francisdb** [comment]
I have seen this happening on mac whit the dmg 

single monitor
FullScreen = 1
b2s window enabled

You can see the playfield window get minimized on startup. Strangely that does not happen when I use the console to launch the table.

Anyway I guess this does not make a lot of sense with a single monitor so for my part this can be closed. New issues can be made on the vpinball repo if this persists.
