### ISSUE TITLE
Alien Nostromo crashing after 15 sec on linux if b2s enabled

### ISSUE THREAD

**Issue by francisdb** [jsm174/vpx-standalone-scripts#110]
Alien Nostromo Ultimate Edition 4.0
https://www.vpforums.org/index.php?app=downloads&showfile=16529

directb2s provided with the table

- Only fails when B2S enabled in ini
- Fails after ~15 seconds of starting the table without doing any interaction
- I tried to debug this but it fails with different traces on each run
- Was not able to reproduce this on macos

These are some of the messages I got printed on console
```
corrupted size vs. prev_size
double free or corruption (out)
malloc(): invalid next size (unsorted)
malloc(): unsorted double linked list corrupted
munmap_chunk(): invalid pointer
```

**Comment by jsm174** [comment]
@francisdb - Is this still an issue? I just played the game for about 5 minutes without any issue. (macos)

**Comment by francisdb** [comment]
Closing for now as I can no longer reproduce this
