### ISSUE TITLE
Hang Glider VPW problems

### ISSUE THREAD

**Issue by toccata10** [jsm174/vpx-standalone-scripts#132]
Hi,
I tried to launch the Hang Glider table from vpw [https://vpuniverse.com/files/file/8056-hang-glider-bally-1976/](url)
First launch indicated a problem with a Dtarray at line 1580.
So, I tried the vpxtool ([https://github.com/francisdb/vpxtool](url)) and did a
`vpxtool frontend` then `Patch typical standalone issues`
No luck: I now have plenty of other problems like `[CodeViewer::AppendLastErrorTextW@3946] Runtime error: Line: 3694, Character: 2, Description unavailable`
I just wanted to let you know.

**Comment by francisdb** [comment]
Will have a look at this one
