### ISSUE TITLE
vbs errors - Earthshaker (Williams 1989)_Bigus(MOD)2.3.vpx

### ISSUE THREAD

**Issue by francisdb** [jsm174/vpx-standalone-scripts#14]
WIP ticket for myself

Did not immediately find the issue

**Comment by jsm174** [comment]
I'm not sure why this table has flexdmd turned on, but if you change:

`Dim UseFlexDMD:UseFlexDMD = False` 

the table runs great.

**Comment by francisdb** [comment]
Thanks! Is there a manual for all these VBS options/hooks that explains what they do?

**Comment by jsm174** [comment]
I wanted to close this, so I started looking at what was going on when `UseFlexDMD` is set to true.

I just filed a bug on the scrrun dictionary in wine:

https://bugs.winehq.org/show_bug.cgi?id=55042

Ironically, 

```
FlexDMDDict.Add 2175,"VPX.DMD_8"
FlexDMDDict.Add 6259, "VPX.DMD_R"
```

2175 and 6259 are generating the same internal hash which is causing a collision on the `Add`

**Comment by francisdb** [comment]
Oh my, that's pretty tricky

**Comment by jsm174** [comment]
So this was actually a Wine vbscript engine issue. It was fixed [here](https://gitlab.winehq.org/wine/wine/-/merge_requests/3064), and discussed [here](https://bugs.winehq.org/show_bug.cgi?id=55042).

This change has been integrated in standalone. 

Standalone was also updated to handle FlexDMD get/put `Bitmap` which now makes this DMD render properly.

Just to note, if you run this table as is, the FlexDMD will not be rendered in VR unless you add the following:

```
--- Earthshaker (Williams 1989)_Bigus(MOD)2.3.vbs.original	
+++ Earthshaker (Williams 1989)_Bigus(MOD)2.3.vbs	
@@ -17,6 +17,7 @@

 Dim VR_Room
 If RenderingMode = 2 Then VR_Room=True Else VR_Room=False      'VRRoom set based on RenderingMode in version 10.72
+VR_Room=True

 LoadVPM "01120100", "S11.VBS", 3.22

\ No newline at end of file
@@ -1021,6 +1022,13 @@
 		End With

 		FlexDMD.UnlockRenderThread
+
+                Dim DMDp: DMDp = FlexDMD.DmdPixels
+                If Not IsEmpty(DMDp) Then
+                   DMDWidth = FlexDMD.Width
+                   DMDHeight = FlexDMD.Height
+                   DMDPixels = DMDp
+                End If

 	End If
  End Sub
  ```

**Comment by francisdb** [comment]
Great, works fine now!
