### ISSUE TITLE
No DMD - PinBot (Williams 1986) 2.1.1

### ISSUE THREAD

**Issue by francisdb** [jsm174/vpx-standalone-scripts#17]
Desktop mode

**Comment by jsm174** [comment]
![Screenshot 2023-06-12 at 7 02 32 PM](https://github.com/jsm174/vpx-standalone-scripts/assets/1197137/80c45edd-a269-483d-a795-7389aa849e70)

This table has alphanumerics and are rendered in VR mode.

**Comment by francisdb** [comment]
But that's not really a solution for ppl that want to play in desktop mode.

**Comment by jsm174** [comment]
We discussed and agreed in chat that the purpose of this repository is to provide the minimum amount of changes required to get the table to run under standalone. It is not about adding new features to a table.
