### ISSUE TITLE
[Script Error] patch: Wheel of Fortune (Stern 2007) 1.0 

### ISSUE THREAD

**Issue by zognic** [jsm174/vpx-standalone-scripts#247]
There is still a script issue with this table
https://github.com/jsm174/vpx-standalone-scripts/pull/77

`ERROR [3487] [CodeViewer::OnScriptError@1180] Script Error at line 584 : VBSE_OUT_OF_BOUNDS`

```vbs
Sub LampTimer_Timer()
    Dim chgLamp, num, chg, ii
    chgLamp = Controller.ChangedLamps
    If Not IsEmpty(chgLamp) Then
        For ii = 0 To UBound(chgLamp)
            LampState(chgLamp(ii, 0) ) = chgLamp(ii, 1)       'keep the real state in an array
            FadingLevel(chgLamp(ii, 0) ) = chgLamp(ii, 1) + 4 'actual fading step
        Next
    End If
	UpdateLamps
End Sub
```

lines 584 & 585
```vbs
             LampState(chgLamp(ii, 0) ) = chgLamp(ii, 1)       'keep the real state in an array
             FadingLevel(chgLamp(ii, 0) ) = chgLamp(ii, 1) + 4 'actual fading step
```

**Comment by francisdb** [comment]
At a first glance this might have something to do with the recent pinmame pwm changes.

**Comment by francisdb** [comment]
@zognic how do I reproduce this error?

I seem to have other strange issues where flippers don't react or are stuck.

**Comment by francisdb** [comment]
What version are you using?

**Comment by zognic** [comment]
> are

Visual Pinball v10.8.0 Beta (Rev. 1880 (c4e2ac8), linux OpenGL 64bits)

**Comment by francisdb** [comment]
Aha yes now this rings a bell, I previously reported this on pinmame
https://github.com/vpinball/pinmame/issues/196

Let me submit my current patch
