### ISSUE TITLE
segmentation fault - Laser War (Data East 1987) w VR Room v2.0.vpx

### ISSUE THREAD

**Issue by francisdb** [jsm174/vpx-standalone-scripts#25]
Needs a bit of gameplay to pop up here

Used the patched vbs in this repo

<img width="744" alt="image" src="https://github.com/jsm174/vpx-standalone-scripts/assets/161305/85a452bd-7fc3-4fa1-819a-40725d37699e">

**Comment by jsm174** [comment]
CoRTracker gBOT vs getballs issue.

Fixed in: https://github.com/jsm174/vpx-standalone-scripts/commit/85b8f787d7a31cc9dcfa63031c0bd860fe02e0fc

**Comment by francisdb** [comment]
see also https://github.com/vpinball/vpinball/issues/1152
