### ISSUE TITLE
Needs patch/fix:  Batman 66 Stern Tribute

### ISSUE THREAD

**Issue by cheese3075** [jsm174/vpx-standalone-scripts#284]
https://vpuniverse.com/files/file/6868-batman-66-stern-tribute%C2%A0/?tab=comments

**Comment by francisdb** [comment]
@cheese3075 this was a deep dive but made it.
Had to fix 2 issues on the vpinball side and one script issue

One everything is merged and with the script fix the table will be able to be played but without Pinup player functionality it's not much fun. Luckily @jsm174 is working on that part, we might see some results of his work in the not so far future. 🙌
