### ISSUE TITLE
PuPlayer.SetLoop - VBSE_ACTION_NOT_SUPPORTED - The Beatles v7

### ISSUE THREAD

**Issue by francisdb** [jsm174/vpx-standalone-scripts#32]
https://orbitalpin.com/downloads/

**Comment by francisdb** [comment]
Not that this table plays properly without pup pack but still not a bad idea to mock that method

**Comment by francisdb** [comment]
Maybe all these can be implemented as `return S_OK;` instead of `return E_NOTIMPL;` ?

**Comment by jsm174** [comment]
> Maybe all these can be implemented as `return S_OK;` instead of `return E_NOTIMPL;` ?
> 
> And log a warning to console?

Yes, I made them as E_NOTIMPL as it helped me find errors quicker and what I needed to implement right away.

Now that we have plog in place I guess could starting logging too.

**Comment by jsm174** [comment]
In the latest version of standalone, I update pup and vpinmame controllers to return `S_OK` and log a warning with `PLOGW`.

The Beatles table you referenced is now playable.

**Comment by francisdb** [comment]
Oh my, that's a lot of logs for `PinUpPlayerPinDisplay::LabelSet@297` :-)
