### ISSUE TITLE
Need Patch for Dune - IOS - no FlexDMD

### ISSUE THREAD

**Issue by Gerhard-BL** [jsm174/vpx-standalone-scripts#334]
FlexDMD in VR-Table

'DMD Hack to include FlexDMD inside the table
Sub ImplicitDMD_Init
   Me.x = 30
   Me.y = 30 
   'Me.fontColor = RGB(255, 255, 255)
   Me.intensityScale = 2
   Me.width = 128 * 2
   Me.height = 32 * 2
   Me.visible = true
   Me.timerenabled = true
End Sub

Sub ImplicitDMD_Timer
   If Not FlexDMD Is Nothing Then
      Dim DMDp: DMDp = FlexDMD.DmdColoredPixels
      If Not IsEmpty(DMDp) Then
         DMDWidth = FlexDMD.Width
         DMDHeight = FlexDMD.Height
         DMDColoredPixels = DMDp
      End If
   End If
End Sub
'End of DMD Hack to include FlexDMD inside the table
![Uploading IMG_1647.png…]()

**Comment by jsm174** [comment]
Please don't request patches. Provide a PR with a patch instead. Also I can't tell if this was meant to be a patch, etc.
