### ISSUE TITLE
Circus Voltair - Patch Script faulty

### ISSUE THREAD

**Issue by Gerhard-BL** [jsm174/vpx-standalone-scripts#336]
Patch Script uses a VAR before it is defined
![IMG_1651](https://github.com/user-attachments/assets/ba62d0d6-1b39-4da7-b776-3351b7e136a0)

**Comment by jsm174** [comment]
Are you trying to suggest a patch? Sorry, not following.

**Comment by Gerhard-BL** [comment]
Please delete this too 
It wasn't the CV Hanibal Mod, was the VPW Version - sorry.

By the way, Hellboy and Dune the DMD isn't working using VPX-IOS (standalone)

**Comment by jsm174** [comment]
Okay, I will close. Btw everything can be made to work... It just requires some elbow grease. 😄
