### ISSUE TITLE
AC-DC LUCI Premium VR (Stern 2013) v1.1 Bell Fix

### ISSUE THREAD

**Issue by M-A-Boucher** [jsm174/vpx-standalone-scripts#337]
The bell in AC-DC LUCI Premium VR (Stern 2013) v1.1 doesn't work because the script tries to set a value to a read-only _id_ ball property (this happened recently?) causing it to crash VPX. Commenting out the lines helps get the table running but the bell won't respond to collisions.

This file fixes this issue by using _userValue_ instead of _id_.
[AC-DC LUCI Premium VR (Stern 2013) v1.1.vbs.zip](https://github.com/user-attachments/files/17788662/AC-DC.LUCI.Premium.VR.Stern.2013.v1.1.vbs.zip)

**Comment by francisdb** [comment]
Is this specific to vpinball standalone?
Might be a better idea to report this at the support link here https://vpuniverse.com/files/file/12471-acdc-luci-stern-2013-vpw-mod/ ?

**Comment by M-A-Boucher** [comment]
Ah, yes, my bad. This is only a problem under 10.8.1 and not under standalone.

**Comment by francisdb** [comment]
@M-A-Boucher I'm going to submit this fix here for now if you don't mind.
