### ISSUE TITLE
Round not fully implemented

### ISSUE THREAD

**Issue by francisdb** [jsm174/vpx-standalone-scripts#45]
There's an issue with new JPSalas tables, spinning devices seem to have 0 friction causing them to spin forever. Arabian Nights and Avengers v5. His v4 tables don't have this issue.

No issue on windows GL latest build

```vbs
    debug.Print sVel
    sVel = Round(sVel, 3)
    debug.Print sVel
```

logs the following

```
2023-07-03 13:45:17.904 INFO  [5275170] [DebuggerModule::Print@4186] Script.Print '6.982'
2023-07-03 13:45:17.904 INFO  [5275170] [DebuggerModule::Print@4186] Script.Print '7'
```

Looks like the rounding `numdecimalplaces` is not implemented properly
```
Round(expression[,numdecimalplaces]) 

numdecimalplaces | Optional. Specifies how many places to the right of the decimal are included in the rounding. | Default is 0
```

**Comment by jsm174** [comment]
wow. great catch. looks like the vbscript engine doesn't even use the other pattern:

```
static HRESULT Global_Round(BuiltinDisp *This, VARIANT *arg, unsigned args_cnt, VARIANT *res)
{
    double n;
    HRESULT hres;

    TRACE("%s\n", debugstr_variant(arg));

    if(!res)
        return S_OK;

    switch(V_VT(arg)) {
    case VT_I2:
    case VT_I4:
    case VT_BOOL:
        *res = *arg;
        return S_OK;
    case VT_R8:
        n = V_R8(arg);
        break;
    default:
        hres = to_double(arg, &n);
        if(FAILED(hres))
            return hres;
    }

    return return_double(res, round(n));
}
```

I'll have to do some test cases, as not sure I'm understanding the rounding.

**Comment by jsm174** [comment]
Turns out there is a function called `VarR8Round` in Wine, so using that seems to work. I'll put the patch in and submit a bug.

**Comment by jsm174** [comment]
I fixed this in the latest standalone:

https://github.com/vpinball/vpinball/blob/7624c3e3281947254f01bb398daca161861dd7bd/standalone/inc/wine/dlls/vbscript/global.c#L3525-L3595

I also submitted a bug on WineHQ:  https://bugs.winehq.org/show_bug.cgi?id=55185
