### ISSUE TITLE
Sounds not working half of the time on some tables

### ISSUE THREAD

**Issue by francisdb** [jsm174/vpx-standalone-scripts#63]
I was testing `Lost World (Bally 1977) 4.0.1`
https://www.vpforums.org/index.php?app=downloads&showfile=12941
You can clearly hear that a lot of the bumper sounds just don't play. Same for the flippers when flippering fast.

Somehow I think this is mostly with JPSalas tables.

This is a remaining issue from earlier but BASS was reverted on master
https://github.com/vpinball/vpinball/issues/572

**Comment by jsm174** [comment]
Closing as this is more a vpinball issue in general.  Thread continued in https://github.com/vpinball/vpinball/issues/572
