### ISSUE TITLE
Plunger.MotionDevice property missing

### ISSUE THREAD

**Issue by francisdb** [jsm174/vpx-standalone-scripts#65]
`Evel Knievel (Bally 1977)_Bigus(MOD) 2.2 `
https://www.vpforums.org/index.php?app=downloads&showfile=15136

```vbscript
If Plunger.MotionDevice>0 Then
```

```
2023-07-19 12:12:31.378 ERROR [3319028] [CodeViewer::OnScriptError@1176] Script Error at line 145 : VBSE_OLE_NO_PROP_OR_METHOD
2023-07-19 12:12:31.378 ERROR [3319028] [CodeViewer::AppendLastErrorTextW@3950] Runtime error: Line: 145, Character: 3, VBSE_OLE_NO_PROP_OR_METHOD
```

https://github.com/vpinball/vpinball/blob/03f386b32b2782b63a331c54b7a94e93b270a972/txt/CommandReference.txt#L693

https://github.com/vpinball/vpinball/blob/03f386b32b2782b63a331c54b7a94e93b270a972/txt/Changelog.txt#L1758

**Comment by jsm174** [comment]
Looks like my IDL parser needs to handle comments after lines:

              [id(6), helpstring("method Position")] HRESULT Position([out, retval] float *pVal); //added for mechanical plunger position, also supports normal/digital one by now
                [id(7), helpstring("method PullBackandRetract")] HRESULT PullBackandRetract(); //added for manual non-mech plunger
                [id(216), helpstring("method MotionDevice")] HRESULT MotionDevice([out, retval] int *pVal); //added for uShockType
                                
`PullBackandRetract` and `MotionDevice` never got implemented..

**Comment by jsm174** [comment]
This is fixed in latest standalone!

**Comment by francisdb** [comment]
Thanks, confirmed fixed
