### ISSUE TITLE
Segfault on "Inhabiting Mars"

### ISSUE THREAD

**Issue by francisdb** [jsm174/vpx-standalone-scripts#78]
Pretty sure this table used to work last time when I submitted the patch

See https://github.com/jsm174/vpx-standalone-scripts/pull/51#issuecomment-1621576209 for the table info, required patch and flexdmd copy code

Just starting the table is enough to make it crash

<img width="713" alt="image" src="https://github.com/jsm174/vpx-standalone-scripts/assets/161305/9723c50e-c4ff-4acc-bd62-97267f14c659">

```
Image::putref_Bitmap(void **) Image.cpp:34
Image::Invoke(int, const _GUID &, unsigned int, unsigned short, tagDISPPARAMS *, tagVARIANT *, tagEXCEPINFO *, unsigned int *) flexdmd_i_proxy.cpp:1659
IDispatch_Invoke oaidl.h:896
disp_propput vbdisp.c:1981
interp_assign_member interp.c:1046
exec_script interp.c:2577
do_icall interp.c:655
interp_icallv interp.c:730
exec_script interp.c:2577
do_icall interp.c:655
interp_icallv interp.c:730
exec_script interp.c:2577
do_icall interp.c:655
interp_icallv interp.c:730
exec_script interp.c:2577
ScriptDisp_InvokeEx vbdisp.c:1698
IDispatchEx_InvokeEx dispex.h:327
ScriptDisp_Invoke vbdisp.c:1637
Timer::FireDispID(int, tagDISPPARAMS *) vpinball_standalone_i_proxy.cpp:5902
EventProxyBase::FireVoidEvent(int) eventproxy.h:14
EventProxy<Timer, &DIID_ITimerEvents>::FireVoidGroupEvent(int) eventproxy.h:83
Timer::FireGroupEvent(int) timer.h:82
Player::UpdatePhysics() player.cpp:2940
Player::OnIdle() player.cpp:4125
VPinball::MainMsgLoop() vpinball.cpp:1530
VPApp::Run() main.cpp:785
WinMain(HINSTANCE, HINSTANCE, LPTSTR, int) main.cpp:1032
main main.cpp:1071
start 0x00000001a8c13f28
```

**Comment by jsm174** [comment]
Yes, sorry about this. I totally overhauled FlexDMD on my last cleanup, which broke this. Please test again in the latest version.

**Comment by francisdb** [comment]
Confirmed fixed but dmd txt is not very readable

<img width="410" alt="image" src="https://github.com/jsm174/vpx-standalone-scripts/assets/161305/e93963a3-ae36-4e1f-95a7-a56494b8d9c4">

Got this from a youtube video:

<img width="410" alt="image" src="https://github.com/jsm174/vpx-standalone-scripts/assets/161305/d9fa0b6b-37a9-4bdb-bebd-b36b2a5297be">

**Comment by jsm174** [comment]
That DMD looks like it has multiple colors. So you need `DmdColoredPixels` instead of `DmdPixels`

So I would probably use: 

```vbs  
   Me.FontColor = RGB(255, 255, 255)
   Me.intensityscale = 3
```
   
And then:

```vbs
    If UseFlexDMD Then
        Dim DMDp: DMDp = FlexDMD.DmdColoredPixels
        If Not IsEmpty(DMDp) Then
            DMDWidth = FlexDMD.Width
            DMDHeight = FlexDMD.Height
            DMDColoredPixels = DMDp
        End If
    End If
```
