### ISSUE TITLE
SpaceRamp ultradmd/flexdmd issues

### ISSUE THREAD

**Issue by francisdb** [jsm174/vpx-standalone-scripts#83]
https://vpuniverse.com/files/file/15682-spaceramp-supered-original-v303b/

Patch on it's way, but the lots of errors regarding `UltraDMD` usage when `turnonultradmd = true`

**Comment by jsm174** [comment]
Fantastic catch!

I forgot to implement the `NewUltraDMD` method in `FlexDMD`.

Fixed in the latest standalone: https://github.com/vpinball/vpinball/commit/8bb1a5bfc2908e841aa49ab6df8b232be9ff1652

**Comment by francisdb** [comment]
All fixed 👏
