### ISSUE TITLE
Make B2S and DMD draggable?

### ISSUE THREAD

**Issue by francisdb** [jsm174/vpx-standalone-scripts#98]
https://stackoverflow.com/questions/58209628/function-to-move-a-sdl2-window-while-mouse-down-flickers-the-window-and-doesnt

Next could be a right click with save option (global / per table)

**Comment by jsm174** [comment]
Thanks to your find we did make the windows draggable a few weeks ago. We also added logging for the changed window position (20ms after the no changes) after Clark Kent's suggestion.
