### ISSUE TITLE
macOS x64 Radeon super slow

### ISSUE THREAD

**Issue by francisdb** [jsm174/vpx-standalone-scripts#99]
- 2,7 GHz Quad-Core Intel Core i7
- 16 GB 2133 MHz LPDDR3
- Radeon Pro 460 4 GB

Check the startup log timestamps

```
2023-09-26 21:12:40.808 INFO  [503379] [Player::Init@2017] Prerendering static parts
2023-09-26 21:12:40.808 INFO  [503379] [VPinball::ProfileLog@2688] Static PreRender Start
2023-09-26 21:20:07.617 INFO  [503379] [VPinball::ProfileLog@2688] AO PreRender Start
2023-09-26 21:20:07.617 INFO  [503379] [VPinball::ProfileLog@2688] Reflection Probe PreRender Start
```

Plays like a slideshow

<img width="1037" alt="image" src="https://github.com/jsm174/vpx-standalone-scripts/assets/161305/cfa2e297-ba54-4f82-9c87-a24373b09408">

_On a side note I see these strange artefacts but I also have that on linux for this table._ 

Tried this but did not change anything. According to  > About this mac my Radeon card is in use.

> If you want to use the higher-performance discrete graphics processor at all times, choose Apple menu  > System Preferences, click Battery, click the Battery tab, then deselect the automatic graphics switching checkbox. In macOS Catalina 10.15 and earlier, this setting is in Energy Saver preferences

**Comment by francisdb** [comment]
This is with default settings, fresh download. Anything I could try to improve things?

**Comment by donaldh** [comment]
Startup time sample:
<img width="903" alt="Pasted Graphic" src="https://github.com/jsm174/vpx-standalone-scripts/assets/465955/3d578ddf-91c0-4c1d-8604-0579647baf37">

Flipper-press in running game:
<img width="938" alt="Pasted Graphic 4" src="https://github.com/jsm174/vpx-standalone-scripts/assets/465955/93fb5d0a-9922-42a8-a88a-5443289c5f66">

**Comment by donaldh** [comment]
It looks to me like every render command triggers a call to the shader compiler.

**Comment by jsm174** [comment]
I initially started this on an Intel Mac Book Pro with nvidia chipset and it worked great. (@scottacus64 could back me up on this). Unfortunately I no longer have any Intel machines. 

Also, I'm not really a graphics person, so I really don't know what could be done. 

You might be able to try playing with these settings:

```
DisableAO = 1
SSRefl = 0
PFReflection = 0
ForceBloomOff = 1
```

**Comment by francisdb** [comment]
Strange artifacts have been reported here https://github.com/vpinball/vpinball/issues/828
